### ISSUE TITLE
Not working in boostrap modal

### ISSUE THREAD

**Issue by mthadian** [ukalpa/inputpicker#39] opened 2019-02-05 07:55 UTC
This is an awesome plugin and thanks for it!!! The plugin works on a normal mark up page but once i put it in a modal it is not showing anymore.

**Comment by ukalpa** [comment] 2019-02-06 19:22
Hi @mthadian ,
Can you please provide more details like the source code of the issue?

**Comment by AndrewPaget** [comment] 2019-03-27 14:53
Was there any resolve to this matter. I too am attempting to make this work inside a Bootstrap Modal, but the Form Element (replacement) does not show in there?

**Comment by ukalpa** [comment] 2019-03-27 18:01
Hi @AndrewPaget ,
Can you please provide the source code of the issue? I am unable to reproduce on my computer.

**Comment by nichter** [comment] 2019-03-29 06:35
Hi Andrew
Please forgive my bad english. i speak spanish and german.
I would like to use this feature on a modal window
therefore i have prepared 2 examples.
I packed a zip file, to use it please unzip this folder beside www folder
inputpicker-master
+--> www
+--->www2 

example
1)   index_modal.php  ----> bootstrap and modal without database support (bootgrid), it works perfectly
2)  index__Databasegrid.php  ----> bootstrap and modal with database support (bootgrid), this has a linl to the source page.

[www2.zip](https://github.com/ukalpa/inputpicker/files/3021386/www2.zip)

I would like to use with database support but i am not able to get it work.

Can you please help me to solve this issue ..

regards !

Carlos

**Comment by ukalpa** [comment] 2019-03-30 21:28
Hi @nichter ,

Please check the file "example-json.php", you load the JSON data from the file "example-districts.json" generated by fetch.php in the file "example-json.php", the problem is you output data as $json["rows"] in the file "example-districts.json" but try to get through $json["data"] in the fie "example-json.php", also it caused you are unable to get the valid $p by the line 28 "if($p > $last_page) $p = $last_page;" due to $last_page is 0, hence, it is the reason you are unable to get the result.

**Comment by KirenJames7** [comment] 2019-04-18 04:49
Hi
Is there a fix for this? I am also experiencing a bug when the element is on a modal. No issue with the UI. But the search input doesn't accept the keyboard input. Even after the value is selected cant you back space or delete to remove it.
[Screencast 2019-04-18 10:18:30.zip](https://github.com/ukalpa/inputpicker/files/3092779/Screencast.2019-04-18.10.18.30.zip)

**Closed** 2019-04-20 01:46 UTC
